### ISSUE TITLE
Install Fails on Mac

### ISSUE THREAD

**Issue by BryanJBryce** [ElmCast/elm-oracle#19]
$ npm install -g elm-oracle
~/.asdf/installs/node/6.2.0/.npm/bin/elm-oracle -> ~/.asdf/installs/node/6.2.0/.npm/lib/node_modules/elm-oracle/bin/elm-oracle

> elm-oracle@1.1.1 postinstall ~/.asdf/installs/node/6.2.0/.npm/lib/node_modules/elm-oracle
> ~/.asdf/installs/node/6.2.0/.npm/lib/node_modules/.hooks/postinstall
> No such plugin
> npm ERR! Darwin 15.4.0
> npm ERR! argh "~/.asdf/installs/node/6.2.0/bin/node" "~/.asdf/installs/node/6.2.0/bin/npm" "install" "-g" "elm-oracle"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE

npm ERR! elm-oracle@1.1.1 postinstall: `~/.asdf/installs/node/6.2.0/.npm/lib/node_modules/.hooks/postinstall`
npm ERR! Exit status 1

**Comment by ivanoats** [comment]
Could you try with node v6.3.0 - it's working on my mac with that.

**Comment by BryanJBryce** [comment]
Same.

**Comment by ajhager** [comment]
@BryanJBryce Does that mean everything works now that you have upgraded to v6.3.0?

**Comment by BryanJBryce** [comment]
No, I'm getting the same error message.

**Comment by BryanJBryce** [comment]
It might be some issue with me having NodeJS installed via https://github.com/asdf-vm/asdf, but I don't know why that would be the case. I'll try setting a global NodeJS version and see if that helps.

**Comment by BryanJBryce** [comment]
Hey, that fixed it.
