### ISSUE TITLE
Update the build on npm?

### ISSUE THREAD

**Issue by deadfoxygrandpa** [ElmCast/elm-oracle#7]
The build that's on npm right now seems old. Is it going to be updated?

**Comment by ajhager** [comment]
The build on npm isn't _old_ really, just that the new build isn't quite ready. The code that is in master uses the experimental elm-node, and since I was traveling the last couple of weeks, I haven't had the time to fully test. The new release should be very soon.

**Comment by deadfoxygrandpa** [comment]
OK, thanks. I understand.

**Comment by jmfirth** [comment]
Bump.  Any ETA for the next release?

**Comment by ajhager** [comment]
elm-oracle 1.1.0 has just been released. The biggest change is errors are returned as json as well now.

**Comment by jmfirth** [comment]
Thanks!
