### ISSUE TITLE
Added to Atom Editor!

### ISSUE THREAD

**Issue by brianegan** [ElmCast/elm-oracle#8]
Hey all, just wanted to thank you for the awesome little repo :) I've added support for Elm-Oracle to the Elm-Language package for atom! It's still in PR, but figured I'd let you all know.

It's still in PR, hoping to get some feedback on it and merge soon! Should I make a PR on this repo that links to the atom-elm package in the README when it's merged?

https://github.com/edubkendo/atom-elm/pull/9

Thanks again!
Brian

**Comment by ajhager** [comment]
Thanks so much! I added a link in the readme.
