### ISSUE TITLE
HTTP_PROXY settings

### ISSUE THREAD

**Issue by ibnHatab** [ElmCast/elm-oracle#9]
elm-oracle doesn't use ENV proxy settings. 

Problem seems to be generic for node http.request, in this case in the `rest` client.
Any hope to solve this issue?

W/O with transparent proxy on linux.
sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to-destination IP:PORT

**Comment by ajhager** [comment]
Elm Oracle 2.0 (which you can track in issue #13) will be removing the need for making web requests. Closing this issue in favor of that one. Thanks again!
